.github/linters/.jscpd.json
.gitignore
build.gradle
config/checkstyle/checkstyle.xml
docker-compose.yaml
lombok.config
scripts/elasticsearch.sh
src/main/java/it/teamdigitale/ndc/config/ElasticsearchClientConfig.java
src/main/java/it/teamdigitale/ndc/config/RestResponseExceptionHandler.java
src/main/java/it/teamdigitale/ndc/controller/VocabularyDataController.java
src/main/java/it/teamdigitale/ndc/data/elasticsearch/repositories/ControlledVocabularyRepository.java
src/main/java/it/teamdigitale/ndc/dto/VocabularyDataDto.java
src/main/java/it/teamdigitale/ndc/service/VocabularyDataService.java
src/main/resources/application.properties
src/test/java/it/teamdigitale/ndc/controller/VocabularyDataControllerTest.java
src/test/java/it/teamdigitale/ndc/integration/VocabularyDataIntegrationTest.java
src/test/java/it/teamdigitale/ndc/service/VocabularyDataServiceTest.java

Co-authored-by: Keerthana <keerthana.r@thoughtworks.com>

61 - exposing APIs for controlled vocabularies

---

src/integration/java/it/teamdigitale/ndc/controller/SemanticAssetsControllerMvcTest.java
src/integration/java/it/teamdigitale/ndc/controller/VocabularyDataControllerMvcTest.java
src/main/java/it/teamdigitale/ndc/model/Builders.java
src/main/java/it/teamdigitale/ndc/model/SemanticAssetsMetadataMapper.java
src/main/java/it/teamdigitale/ndc/service/VocabularyDataService.java
src/main/resources/public/api-docs.yaml
src/test/java/it/teamdigitale/ndc/controller/VocabularyDataControllerTest.java

closes #2  - Changes offset and limit datatypes to int32

closes #2  - Changes offset and limit datatypes to int32

---

build.gradle

This is due to an RCE CVE: https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement

Bump Spring Boot to 2.6.6

---

.github/workflows/publiccode-validation.yml

Bump publiccode action

---

src/main/resources/application-local.properties

- Add documentation for NDC_BASEURL
- Remove dependency from external repository

Fix: #48. Add documentation, remove external repository reference.

---

src/main/resources/META-INF/additional-spring-configuration-metadata.json

- improve harvester.repositories documentation.

Improve harverster.repositories documentation. See #50

---

src/main/resources/public/api-docs.yaml

- improvesa API description
Fixes #32

Fix: #32. Update metadata.

---

build.gradle
src/integration/java/it/gov/innovazione/ndc/controller/VocabularyDataControllerMvcTest.java
src/main/java/it/gov/innovazione/ndc/controller/exception/RestExceptionHandler.java
src/main/java/it/gov/innovazione/ndc/harvester/model/BaseSemanticAssetModel.java
src/main/java/it/gov/innovazione/ndc/harvester/model/SchemaModel.java
src/main/java/it/gov/innovazione/ndc/harvester/model/index/SemanticAssetMetadata.java
src/main/java/it/gov/innovazione/ndc/model/profiles/Admsapit.java
src/main/java/it/gov/innovazione/ndc/repository/TripleStoreRepository.java
src/main/java/it/gov/innovazione/ndc/repository/VirtuosoClient.java
src/main/resources/application-local.properties
src/main/resources/public/api-docs.yaml
src/test/java/it/gov/innovazione/ndc/controller/exception/RestExceptionHandlerTest.java
src/test/java/it/gov/innovazione/ndc/harvester/model/BaseSemanticAssetModelTest.java
src/test/java/it/gov/innovazione/ndc/harvester/model/SchemaModelTest.java
src/test/java/it/gov/innovazione/ndc/repository/TripleStoreRepositoryTest.java
src/test/java/it/gov/innovazione/ndc/repository/VirtuosoClientTest.java

Upgrade jena dependencies

---

CONTRIBUTING.md
build.gradle
config/dependency-check/dependency-check-known-issues.xml
src/test/java/it/gov/innovazione/ndc/harvester/model/ControlledVocabularyModelTest.java
src/test/java/it/gov/innovazione/ndc/harvester/model/OntologyModelTest.java
src/test/java/it/gov/innovazione/ndc/harvester/model/SchemaModelTest.java

this commit is totally unnecessary but will trigger the pipeline again

---

build.gradle
lombok.config
src/main/java/it/gov/innovazione/ndc/config/SecurityConfiguration.java
src/main/java/it/gov/innovazione/ndc/controller/HarvestJobController.java
src/main/java/it/gov/innovazione/ndc/harvester/HarvesterJob.java
src/main/resources/application-local.properties

Questa PR implementa la soluzione 2.
Nello specifico:
- rimuove la schedulazione dell'harvester
- abilita il controller dell'harvester per default
- aggiunge l'autenticazione agli endpoint dell'harvester
@CreaIstat

Feature: soluzione 2 harvester

---

src/main/java/it/gov/innovazione/ndc/Application.java
src/main/java/it/gov/innovazione/ndc/config/BatchConfiguration.java
src/main/java/it/gov/innovazione/ndc/harvester/HarvesterJob.java
src/main/java/it/gov/innovazione/ndc/repository/HarvestJobException.java
src/test/java/it/gov/innovazione/ndc/harvester/HarvesterJobTest.java

Async harvesting

---

build.gradle
src/integration/java/it/gov/innovazione/ndc/integration/RestApiIntegrationTests.java
src/main/java/it/gov/innovazione/ndc/harvester/HarvesterJob.java
src/main/java/it/gov/innovazione/ndc/harvester/model/BaseSemanticAssetModel.java
src/main/java/it/gov/innovazione/ndc/harvester/model/ControlledVocabularyModel.java
src/main/java/it/gov/innovazione/ndc/harvester/model/OntologyModel.java
src/main/java/it/gov/innovazione/ndc/harvester/model/SchemaModel.java
src/main/java/it/gov/innovazione/ndc/repository/TripleStoreRepository.java
src/main/resources/application-local.properties
src/test/java/it/gov/innovazione/ndc/repository/TripleStoreRepositoryTest.java

Cancellazione dati da Virtuoso con log_enable=3
Aumento dei dettagli in caso di errore su virtuoso
@CreaIstat

Cancellazione alternativa harvester

---

build.gradle
src/main/java/it/gov/innovazione/ndc/controller/CheckUrlController.java

check URL API

---

build.gradle
config/dependency-check/dependency-check-known-issues.xml
src/main/java/it/gov/innovazione/ndc/controller/CheckUrlController.java

Check URL Api episode 2

---

docs/diagrams/distribution-urls.puml
src/main/java/it/gov/innovazione/ndc/harvester/SemanticAssetType.java

This PR will mark all semantic types to ignore obsolete versions
@CreaIstat

feat: all types ignore obsolete versions

---

src/main/java/it/gov/innovazione/ndc/config/SimpleHarvestRepositoryProcessor.java
src/main/java/it/gov/innovazione/ndc/controller/HarvestJobController.java
src/main/java/it/gov/innovazione/ndc/controller/RunningInstance.java
src/main/java/it/gov/innovazione/ndc/harvester/service/HarvesterRunService.java

Delete pending endpoint

---

src/main/java/it/gov/innovazione/ndc/controller/OffsetBasedPageRequest.java
src/main/java/it/gov/innovazione/ndc/repository/SemanticAssetMetadataRepository.java
src/main/resources/public/openapi.yaml

- fixes pagination
- added "ISSUED_ON" as a sort property
@CreaIstat 
@mspist

Requisito Extraction

---

build.gradle
src/main/java/it/gov/innovazione/ndc/controller/RepositoryController.java
src/main/java/it/gov/innovazione/ndc/harvester/HarvesterJob.java
src/main/java/it/gov/innovazione/ndc/harvester/service/RepositoryService.java
src/main/java/it/gov/innovazione/ndc/model/harvester/Repository.java

fixes minor issues

---

src/main/java/it/gov/innovazione/ndc/controller/RepositoryController.java
src/main/java/it/gov/innovazione/ndc/harvester/service/RepositoryService.java
src/main/java/it/gov/innovazione/ndc/model/harvester/Repository.java

Clean repo on repo deletion

---

src/main/java/it/gov/innovazione/ndc/harvester/service/RepositoryService.java
src/test/java/it/gov/innovazione/ndc/harvester/service/RepositoryServiceTest.java

added default key to lang if "it" and "en" are missing

---

src/main/java/it/gov/innovazione/ndc/harvester/model/extractors/RightsHolderExtractor.java
src/main/java/it/gov/innovazione/ndc/harvester/service/RepositoryService.java

identifiers for agencyId to lowercase

---

src/main/java/it/gov/innovazione/ndc/harvester/HarvesterJob.java
src/main/java/it/gov/innovazione/ndc/harvester/service/RepositoryService.java
src/main/java/it/gov/innovazione/ndc/model/harvester/Repository.java

fixes #102 
@CreaIstat @mspist

small fixes

---

src/main/java/it/gov/innovazione/ndc/eventhandler/event/HarvestedFileTooBigEvent.java
src/main/java/it/gov/innovazione/ndc/harvester/harvesters/BaseSemanticAssetHarvester.java
src/main/java/it/gov/innovazione/ndc/harvester/service/ConfigService.java
src/test/java/it/gov/innovazione/ndc/harvester/harvesters/BaseSemanticAssetHarvesterTest.java
src/test/java/it/gov/innovazione/ndc/harvester/harvesters/ControlledVocabularyHarvesterTest.java
src/test/java/it/gov/innovazione/ndc/harvester/harvesters/OntologyHarvesterTest.java
src/test/java/it/gov/innovazione/ndc/harvester/harvesters/SchemaHarvesterTest.java

fixes per file scanner

---

CODE_OF_CONDUCT.md

Deleting mentions to Developers Italia
CC: @Clou-dia @mauropratesi

Changes to CODE_OF_CONDUCT.md

---

CONTRIBUTING.md

Updating the file with the same changes of teamdigitale/dati-semantic-frontend#530
CC: @Clou-dia @mauropratesi

Update contributing file with same changes as front-end repo

---

src/main/java/it/gov/innovazione/ndc/service/GithubService.java

minor log message change

---

src/integration/java/it/gov/innovazione/ndc/integration/TestingDataSourceConfig.java
src/main/java/it/gov/innovazione/ndc/alerter/data/EntityService.java
src/main/java/it/gov/innovazione/ndc/alerter/data/initializer/DataInitializer.java
src/main/java/it/gov/innovazione/ndc/alerter/data/initializer/DefaultInitializer.java
src/main/java/it/gov/innovazione/ndc/alerter/data/initializer/InitializerConfiguration.java

fixing create default profiles at startup

---

src/main/java/it/gov/innovazione/ndc/alerter/controller/AbstractCrudController.java
src/main/java/it/gov/innovazione/ndc/alerter/controller/EventController.java
src/main/java/it/gov/innovazione/ndc/alerter/data/ProfileMapper.java
src/main/java/it/gov/innovazione/ndc/alerter/dto/EventDto.java
src/main/java/it/gov/innovazione/ndc/alerter/dto/ProfileDto.java

fixes some small issues found during peer review

---

src/main/java/it/gov/innovazione/ndc/alerter/AlerterService.java
src/main/java/it/gov/innovazione/ndc/alerter/data/EventMapper.java
src/main/java/it/gov/innovazione/ndc/alerter/data/ProfileService.java
src/main/java/it/gov/innovazione/ndc/service/AlerterMailSender.java

fixes event window

---

src/main/java/it/gov/innovazione/ndc/service/AlerterMailSender.java
src/main/resources/templates/alerter_mail_template.html

Europe/Rome timezone for createdAt in emails, minor fixes

---

src/main/java/it/gov/innovazione/ndc/service/AlerterMailSender.java
src/main/resources/application.properties

adds configurable interval for alerter job
